### ISSUE TITLE
ripgrep lookup from a $PATH

### ISSUE THREAD

**Issue by autoclcker** [joshmu/periscope#70]
Hello, thanks for the great extension.

I would like to suggest the idea of using ripgrep from the $PATH variable. As in other extensions. Eventually delete the search for the /usr/local/bin/rg file

**Comment by joshmu** [comment]
Hey @autoclcker,

Thanks for your suggestion! Let me clarify how ripgrep path resolution currently works in Periscope:

1. First, we check if the user has provided a custom ripgrep path via the `periscope.rgPath` setting
2. If no custom path is specified, we use the `@vscode/ripgrep` package's bundled binary

We don't actually search `/usr/local/bin/rg` this is just an option for the user if they want to point to their own rg binary - instead by default we rely on the official VSCode ripgrep package which:
- Ensures a consistent, tested version of ripgrep is available
- Handles cross-platform compatibility automatically
- Doesn't depend on system-level installations

Could you help me understand your use case for preferring the system PATH ripgrep over the bundled version? This would help better evaluate the suggestion.

Thanks!

**Comment by autoclcker** [comment]
I relied on the description of the extension (/usr/local/bin/rg) in settings:
![image](https://github.com/user-attachments/assets/64377352-4492-4a42-a840-12a3f49e0605)

If I don't specify the exact path, ripgrep will return an error message:
![image](https://github.com/user-attachments/assets/82038072-4c92-4c8c-95ec-5ca2ed83aaa3)

I use VSCodium. In most cases, extensions are backward compatible with extensions for vscode. As I see it, I'm getting a ripgrep version for a different architecture (Mac OS), while I'm on Linux:
![image](https://github.com/user-attachments/assets/aced6f0d-7621-4b1d-afa7-255a829a4f62)

**Comment by joshmu** [comment]
Ah ok got it.

**VSCodium** uses **open-vsx.org** to manage extensions which at one point I had stopped publishing to because it did not support publishing platform specific variants of the extension.

Good news is this is no longer the case so I have made the necessary updates.  You should be now receiving the correct ripgrep binary when installing the extension on VSCodium.

https://open-vsx.org/extension/JoshMu/periscope

**Before:**
<img width="211" alt="image" src="https://github.com/user-attachments/assets/5facb80c-36cc-417e-bf55-d691c65537f9" />
**After:**
<img width="351" alt="image" src="https://github.com/user-attachments/assets/76fbc6cd-c423-4973-a507-273a591f068a" />

Let me know if its all good now on your end when you remove the explicit rg path requirement.

**Comment by autoclcker** [comment]
Now it looks perfect!

Thanks
